### ISSUE TITLE
issue with graphical overmap mod

### ISSUE THREAD

**Issue by fire78** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#15]
![image](https://user-images.githubusercontent.com/73866728/105795097-438de480-5f5a-11eb-9198-64bca9d8a2b3.png)

this happens every time i try to play i followed the read me and I don't no why this is happening

**Comment by CV514** [comment]
Can't reproduce. Are you sure you're using Cataclysm Bright Nights? It comes in mind since there is no trailhead_shack_z0 in stable release of CDDA (not Bright Nights); basically, if you're rolling with mod packs, you're should be on experimental and latest releases, and this modpack is specifically for Bright Nights fork.

Also, don't forget you should make changes into your font config according to [Graphical Overmap readme](https://raw.githubusercontent.com/Kenan2000/Bright-Nights-Kenan-Mod-Pack/master/Kenan-BrightNights-Modpack/Graphical_Overmap/readme.txt), but even without this you shouldn't receive this error, you simply won't have map tileset.

How should it look when everything is set up correctly:
![graphmap](https://user-images.githubusercontent.com/60776130/105892271-d3f02600-603b-11eb-8d11-574428a5a9b8.png)

**Comment by Kenan2000** [comment]
@fire78 just published an update that removes the `Graphical_Overmap` mods from the Bright Nights Modpack, the latest Bright Nights releases are always prepackaged with ready to use Graphical Overmap mods and are all maintained by Bright Nights main developer - Coolcthulhu/BroadFlatNails, so no need for us to maintain these

Now, if you enable the versions of `Graphical_Overmap` that are prepackaged in the latest releases of Bright Nights, you should not be experiencing any errors or problems :-)

**Comment by fire78** [comment]
i figured it out already forgot to post on here i asked for help on the cdda discord thanks for the help anyway
